services:
  - type: web
    name: upcyclica-api
    runtime: python
    buildCommand: ""
    startCommand: uvicorn main:app --host=0.0.0.0 --port=10000
    rootDir: backend         # 👈 Add this line
    envVars:
      - key: DATABASE_URL
        fromEnv: true
      - key: CLOUDINARY_API_KEY
        fromEnv: true
      - key: OPENAI_API_KEY
        fromEnv: true
    plan: free
